apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Hello World sample application
  sourceRepos:
    - '*'
  destinations:
    - namespace: hello-world
      server: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  roles:
    - name: sync-role
      description: Privileges to manually sync hello-world apps
      policies:
        - p, proj:hello-world:sync-role, applications, sync, hello-world/*, allow
      groups:
        - dev-team
    - name: admin
      description: Admin access to hello-world apps
      policies:
        - p, proj:hello-world:admin, applications, *, hello-world/*, allow
      groups:
        - platform-team
