apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster-b.hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hello-world
  source:
    repoURL: git@github.com:your-org/k8s-deployments.git
    targetRevision: main
    path: manifests/hello-world/clusters/prod-cluster-b
  destination:
    name: prod-cluster-b
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
