apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-b.infra-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: dev-cluster-b
    namespace: argocd
  source:
    path: infra-apps/clusters/dev-cluster-b
    repoURL: git@github.com:your-org/k8s-deployments.git
    targetRevision: main
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
