apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  # Dev clusters - apps
  - apps-dev-cluster-a.yaml
  - apps-dev-cluster-b.yaml
  # Dev clusters - infra apps
  - infra-apps-dev-cluster-a.yaml
  - infra-apps-dev-cluster-b.yaml
