apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster-a.apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: prod-cluster-a
    namespace: argocd
  source:
    path: apps/clusters/prod-cluster-a
    repoURL: git@github.com:your-org/k8s-deployments.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
