apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  # Prod clusters - apps
  - apps-prod-cluster-a.yaml
  - apps-prod-cluster-b.yaml
  # Prod clusters - infra apps
  - infra-apps-prod-cluster-a.yaml
  - infra-apps-prod-cluster-b.yaml
