apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kty-sbx-daisy.nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nginx
  source:
    repoURL: https://github.com/deegupt4/k8s-deploy-argo.git
    targetRevision: main
    path: manifests/nginx/clusters/kty-sbx-daisy
  destination:
    name: kty-sbx-daisy
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
