apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-b.cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.0
    chart: cert-manager
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    name: dev-cluster-b
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
